kramdown:
  parse_block_html: true

collections:
  tutoriels:
      output: true

defaults:
  - scope:
      path: ""
      type: "tutoriels"
    values:
      layout: "tutoriel"
  - scope:
      path: ""
    values:
      layout: "default"
